python train.py \
    --pretrained_model "uer/t5-base-chinese-cluecorpussmall" \
    --save_dir "D:/Jupyter notebook file/硕士/PLM/Text Generation/Filling Model" \
    --train_path "D:/Data/master/Freshmen Coding Assignment/NLP/DuReaderQG/train.tsv" \
    --dev_path "D:/Data/master/Freshmen Coding Assignment/NLP/DuReaderQG/dev.tsv" \
    --img_log_dir "D:/Jupyter notebook file/硕士/PLM/Text Generation/Filling Model" \
    --img_log_name "T5-Base-Chinese" \
    --batch_size 128 \
    --max_source_seq_len 64 \
    --max_target_seq_len 32 \
    --learning_rate 1e-4 \
    --num_train_epochs 15 \
    --logging_steps 50 \
    --valid_steps 250 \
    --device cpu